name: Playwright Tests

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'What to test?'
        required: true
        default: 'login'
        type: choice
        options:
          - all
          - login

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{ secrets.USER_NAME }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Determine test command
      id: test-command
      run: |
        if [ "${{ inputs.test_type }}" == "all" ]; then
          echo "COMMAND=npx playwright test --reporter=html" >> $GITHUB_OUTPUT
        else
          echo "COMMAND=npx playwright test login.spec.ts --reporter=html" >> $GITHUB_OUTPUT
        fi
    
    - name: Run Playwright tests
      run: ${{ steps.test-command.outputs.COMMAND }}
    
    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        if-no-files-found: ignore